# ==============================================================================
# NetCore User Configuration
# ==============================================================================

hostname: network-server

timezone: America/Chicago


network:

  ip: 192.168.0.250

  subnet: 192.168.0.0/24

  gateway: 192.168.0.1

  dns: 192.168.0.250


features:

  tailscale:
    enabled: true

  adguard:
    enabled: true

  unbound:
    enabled: true

  cockpit:
    enabled: true

  docker:
    enabled: true

  uptime_kuma:
    enabled: true

  netdata:
    enabled: true
